---
# tasks file for packdocker

- name: adding apt key
  apt_key:
    url: "{{ url }}"
    state: present
  when: url != ""

- name: adding repository
  apt_repository:
    repo: "{{ repo }}"
    filename: "{{ filename }}"
    state: present
  when: repo != ""

- name: installing package
  apt:
    name: "{{ package }}"
    state: latest
    update_cache: yes

- name: start and enable the service
  service:
    name: "{{ service }}"
    state: started
    enabled: yes
  when: service != ""
